version: '1.0'
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: pnpm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development